- name: Install haproxy
  apt:
    pkg: haproxy
    state: latest
    update_cache: true
- name: Configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 644
- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    enabled: yes