- name: install etcd
  apt:
    pkg: etcd
    state: latest
    update_cache: true
- name: install etcd config
  template:
    src: templates/etcd.j2
    dest: /etc/default/etcd
    mode: 644
- name: restart etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes

